services:
  cs16:
    image: ttkirby/cs15
    container_name: ttkirby-counter-strike-1.6-server
    ports:
      - 80:80
      - 27015:27015/udp
    environment:
# PACK INSTALLER
      - REHLDS=
      - METAMOD=true
      - AMXMODX=true
      - FASTDL=true
# ADMINISTRATION
      - HOSTNAME=ttKirby's Counter-Strike 1.6 Server
      - PASSWORD=
      - RCON=
      - STEAM_ID=STEAM_0:1:12345678
# START PARAMETER
      - SV_LAN=0
      - MAP=de_dust2
      - PLAYERS=16
# PODBot & YaPB & ZBot
      - BOTS=YaPB
    volumes:
      - ./hlds:/hlds
    restart: unless-stopped
